name: Ping Service

on:
  schedule:
    - cron: '*/10 * * * *'  # Executes every 10 minutes

jobs:
  ping-service:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Endpoint
        run: |
          curl -s https://doc-ping.vercel.app/
          echo "Pinged the service successfully!"
