name: Periodic Ping

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Service
        run: curl -X GET https://doc-ping.vercel.app/
